<a href="https://colab.research.google.com/github/maryom99/academicIS/blob/master/My_first_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
name = "Maryam Mohammed Ali Albaiti"
nim = 2041720205

print("name = ", name, "\n", "nim = ", nim)

name =  Maryam Mohammed Ali Albaiti
 nim =  2041720205

In [1]:
pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.2.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [2]:
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import csv

dataset = '/content/sample_data/Data1.csv'
with open(dataset) as inisial_file:
   baca_file = csv.reader(inisial_file, delimiter=',')
   for baris in baca_file:
     print(baris)

['\ufeffOrderDate', 'Region', 'Rep', 'Item', 'Units', 'Unit Cost', 'Total']
['1/6/21', 'East', 'Jones', 'Pencil', '95', ' 1.99 ', ' 189.05 ']
['1/23/21', 'Central', 'Kivell', 'Binder', '50', ' 19.99 ', ' 999.50 ']
['2/9/21', 'Central', 'Jardine', 'Pencil', '36', ' 4.99 ', ' 179.64 ']
['2/26/21', 'Central', 'Gill', 'Pen', '27', ' 19.99 ', ' 539.73 ']
['3/15/21', 'West', 'Sorvino', 'Pencil', '56', ' 2.99 ', ' 167.44 ']
['4/1/21', 'East', 'Jones', 'Binder', '60', ' 4.99 ', ' 299.40 ']
['4/18/21', 'Central', 'Andrews', 'Pencil', '75', ' 1.99 ', ' 149.25 ']
['5/5/21', 'Central', 'Jardine', 'Pencil', '90', ' 4.99 ', ' 449.10 ']
['5/22/21', 'West', 'Thompson', 'Pencil', '32', ' 1.99 ', ' 63.68 ']
['6/8/21', 'East', 'Jones', 'Binder', '60', ' 8.99 ', ' 539.40 ']
['6/25/21', 'Central', 'Morgan', 'Pencil', '90', ' 4.99 ', ' 449.10 ']
['7/12/21', 'East', 'Howard', 'Binder', '29', ' 1.99 ', ' 57.71 ']
['7/29/21', 'East', 'Parent', 'Binder', '81', ' 19.99 ', ' 1,619.19 ']
['8/15/21', 'East', 'Jones', 'Pencil', '35', ' 4.99 ', ' 174.65 ']
['9/1/21', 'Central', 'Smith', 'Desk', '2', ' 125.00 ', ' 250.00 ']
['9/18/21', 'East', 'Jones', 'Pen Set', '16', ' 15.99 ', ' 255.84 ']
['10/5/21', 'Central', 'Morgan', 'Binder', '28', ' 8.99 ', ' 251.72 ']
['10/22/21', 'East', 'Jones', 'Pen', '64', ' 8.99 ', ' 575.36 ']
['11/8/21', 'East', 'Parent', 'Pen', '15', ' 19.99 ', ' 299.85 ']
['11/25/21', 'Central', 'Kivell', 'Pen Set', '96', ' 4.99 ', ' 479.04 ']
['12/12/21', 'Central', 'Smith', 'Pencil', '67', ' 1.29 ', ' 86.43 ']
['12/29/21', 'East', 'Parent', 'Pen Set', '74', ' 15.99 ', ' 1,183.26 ']
['1/15/22', 'Central', 'Gill', 'Binder', '46', ' 8.99 ', ' 413.54 ']
['2/1/22', 'Central', 'Smith', 'Binder', '87', ' 15.00 ', ' 1,305.00 ']
['2/18/22', 'East', 'Jones', 'Binder', '4', ' 4.99 ', ' 19.96 ']
['3/7/22', 'West', 'Sorvino', 'Binder', '7', ' 19.99 ', ' 139.93 ']
['3/24/22', 'Central', 'Jardine', 'Pen Set', '50', ' 4.99 ', ' 249.50 ']
['4/10/22', 'Central', 'Andrews', 'Pencil', '66', ' 1.99 ', ' 131.34 ']
['4/27/22', 'East', 'Howard', 'Pen', '96', ' 4.99 ', ' 479.04 ']
['5/14/22', 'Central', 'Gill', 'Pencil', '53', ' 1.29 ', ' 68.37 ']
['5/31/22', 'Central', 'Gill', 'Binder', '80', ' 8.99 ', ' 719.20 ']
['6/17/22', 'Central', 'Kivell', 'Desk', '5', ' 125.00 ', ' 625.00 ']
['7/4/22', 'East', 'Jones', 'Pen Set', '62', ' 4.99 ', ' 309.38 ']
['7/21/22', 'Central', 'Morgan', 'Pen Set', '55', ' 12.49 ', ' 686.95 ']
['8/7/22', 'Central', 'Kivell', 'Pen Set', '42', ' 23.95 ', ' 1,005.90 ']
['8/24/22', 'West', 'Sorvino', 'Desk', '3', ' 275.00 ', ' 825.00 ']
['9/10/22', 'Central', 'Gill', 'Pencil', '7', ' 1.29 ', ' 9.03 ']
['9/27/22', 'West', 'Sorvino', 'Pen', '76', ' 1.99 ', ' 151.24 ']
['10/14/22', 'West', 'Thompson', 'Binder', '57', ' 19.99 ', ' 1,139.43 ']
['10/31/22', 'Central', 'Andrews', 'Pencil', '14', ' 1.29 ', ' 18.06 ']
['11/17/22', 'Central', 'Jardine', 'Binder', '11', ' 4.99 ', ' 54.89 ']
['12/4/22', 'Central', 'Jardine', 'Binder', '94', ' 19.99 ', ' 1,879.06 ']
['12/21/22', 'Central', 'Andrews', 'Binder', '28', ' 4.99 ', ' 139.72 ']

In [10]:
import pandas as pd
dataset = pd.read_csv('/content/drive/MyDrive/Machine Learning/Data1.csv')
dataset

   OrderDate   Region       Rep     Item  Units  Unit Cost       Total
0     1/6/21     East     Jones   Pencil     95       1.99     189.05
1    1/23/21  Central    Kivell   Binder     50      19.99     999.50
2     2/9/21  Central   Jardine   Pencil     36       4.99     179.64
3    2/26/21  Central      Gill      Pen     27      19.99     539.73
4    3/15/21     West   Sorvino   Pencil     56       2.99     167.44
5     4/1/21     East     Jones   Binder     60       4.99     299.40
6    4/18/21  Central   Andrews   Pencil     75       1.99     149.25
7     5/5/21  Central   Jardine   Pencil     90       4.99     449.10
8    5/22/21     West  Thompson   Pencil     32       1.99      63.68
9     6/8/21     East     Jones   Binder     60       8.99     539.40
10   6/25/21  Central    Morgan   Pencil     90       4.99     449.10
11   7/12/21     East    Howard   Binder     29       1.99      57.71
12   7/29/21     East    Parent   Binder     81      19.99   1,619.19
13   8/15/21     East     Jones   Pencil     35       4.99     174.65
14    9/1/21  Central     Smith     Desk      2     125.00     250.00
15   9/18/21     East     Jones  Pen Set     16      15.99     255.84
16   10/5/21  Central    Morgan   Binder     28       8.99     251.72
17  10/22/21     East     Jones      Pen     64       8.99     575.36
18   11/8/21     East    Parent      Pen     15      19.99     299.85
19  11/25/21  Central    Kivell  Pen Set     96       4.99     479.04
20  12/12/21  Central     Smith   Pencil     67       1.29      86.43
21  12/29/21     East    Parent  Pen Set     74      15.99   1,183.26
22   1/15/22  Central      Gill   Binder     46       8.99     413.54
23    2/1/22  Central     Smith   Binder     87      15.00   1,305.00
24   2/18/22     East     Jones   Binder      4       4.99      19.96
25    3/7/22     West   Sorvino   Binder      7      19.99     139.93
26   3/24/22  Central   Jardine  Pen Set     50       4.99     249.50
27   4/10/22  Central   Andrews   Pencil     66       1.99     131.34
28   4/27/22     East    Howard      Pen     96       4.99     479.04
29   5/14/22  Central      Gill   Pencil     53       1.29      68.37
30   5/31/22  Central      Gill   Binder     80       8.99     719.20
31   6/17/22  Central    Kivell     Desk      5     125.00     625.00
32    7/4/22     East     Jones  Pen Set     62       4.99     309.38
33   7/21/22  Central    Morgan  Pen Set     55      12.49     686.95
34    8/7/22  Central    Kivell  Pen Set     42      23.95   1,005.90
35   8/24/22     West   Sorvino     Desk      3     275.00     825.00
36   9/10/22  Central      Gill   Pencil      7       1.29       9.03
37   9/27/22     West   Sorvino      Pen     76       1.99     151.24
38  10/14/22     West  Thompson   Binder     57      19.99   1,139.43
39  10/31/22  Central   Andrews   Pencil     14       1.29      18.06
40  11/17/22  Central   Jardine   Binder     11       4.99      54.89
41   12/4/22  Central   Jardine   Binder     94      19.99   1,879.06
42  12/21/22  Central   Andrews   Binder     28       4.99     139.72